apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::539716262368:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3L9O03E3WCFJ
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::539716262368:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-04T22:53:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "860"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 713f2d04-5e2f-42ad-8762-4ec824b6ff1a
