apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::539716262368:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-05T19:16:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15584"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 97fabeaf-0794-4014-9803-3deeb251cf68
